### ISSUE TITLE
V2: Make HuBMAP Logo Clickable

### ISSUE THREAD

**Issue by DerekFurstPitt** [hubmapconsortium/data-ingest-board#41]

**Comment by yuanzhou** [comment]
Logo was linked to ingest-ui, and later removed the link based on below discussion:

<img width="1313" alt="Screenshot 2023-08-29 at 9 21 18 PM" src="https://github.com/hubmapconsortium/data-ingest-board/assets/195873/24fb50a3-d385-47e8-bcfb-1012e6773140">
