### ISSUE TITLE
Coordinate status colors between ingest-ui and ingest-board.

### ISSUE THREAD

**Issue by DerekFurstPitt** [hubmapconsortium/data-ingest-board#53]
Verify status color choices are consistent between ingest-ui and the data ingest board.

**Comment by yuanzhou** [comment]
Addressed by @libpitt via PR https://github.com/hubmapconsortium/data-ingest-board/pull/76 and released via PR https://github.com/hubmapconsortium/data-ingest-board/pull/77

FYI @shirey @DerekFurstPitt
