### ISSUE TITLE
Add updated message with instructions for registered users without proper access

### ISSUE THREAD

**Issue by maxsibilla** [hubmapconsortium/data-ingest-board#88]
Related to this card: https://github.com/sennetconsortium/portal-ui/issues/947

We want to add a similar message but will change the links and distinguish between HuBMAP and SenNet.

**Comment by maxsibilla** [comment]
```
You are trying to access the <SenNet/HuBMAP> Data Ingest Board logged in as <users email>.
You are not authorized to log into this application with that account.  Please check that
you have registered via the <Member Registration Page>, have provided Globus account
information and are logging in with that account.

Once you have confirmed your registration information you can <log in> again.

If you continue to have issues accessing this site please contact the <<SenNet/HuBMAP> Help Desk>.
```

Link "Member Registration Page" to https://profile.sennetconsrotium.org/profile or https://profile.hubmapconsortium.org/profile
Link "log in" to the login link 
Link "SenNet/HuBMAP Help Desk" to [help@sennetconsortium.org](mailto:help@sennetconsortium.org) or [help@hubmapconsortium.org](mailto:help@hubmapconsortium.org)

**Comment by libpitt** [comment]
![unauthorized](https://github.com/hubmapconsortium/data-ingest-board/assets/115558393/4b041959-4825-43d2-acd0-36845c0fbd97)

**Comment by libpitt** [comment]
![HM-unauthorized](https://github.com/hubmapconsortium/data-ingest-board/assets/115558393/9c358457-7b20-4e8a-9da5-b57c9be04e6f)

**Comment by yuanzhou** [comment]
Released for HuBMAP: https://github.com/hubmapconsortium/data-ingest-board/releases/tag/v1.2.4
