### ISSUE TITLE
Show user's email next to "Log Out" similar to how the Ingest UI and SenNet Portal do

### ISSUE THREAD

**Issue by maxsibilla** [hubmapconsortium/data-ingest-board#89]

**Comment by libpitt** [comment]
![HuBMAP-sm](https://github.com/hubmapconsortium/data-ingest-board/assets/115558393/65ca6b3d-5fd1-49b2-b4fb-ed2f9660a756)
![SenNet-lg](https://github.com/hubmapconsortium/data-ingest-board/assets/115558393/c7ed77d3-acc0-4bab-a2cd-700850db6328)
![SenNet-sm](https://github.com/hubmapconsortium/data-ingest-board/assets/115558393/ce2a2c7f-244c-4bfa-912d-fa77ffe4cb55)

**Comment by libpitt** [comment]
@maxsibilla Had to refactor with the react-bootstrap `Nav` component as things were no longer fitting.

**Comment by yuanzhou** [comment]
Released for HuBMAP: https://github.com/hubmapconsortium/data-ingest-board/releases/tag/v1.2.4
